common/common.c
See [this Discord message](https://discord.com/channels/1152022492001603615/1261339446570385439/1265344781291225150) for additional context.
It appears that when comparing two strings of different length where one is a prefix of the other (like "GB" and "GBA", etc.), `str_compare` currently returns 0 (equal) rather than sorting the shorter string before the longer one.
This leads to things like names in the content list (e.g., folder pairs like "Game Boy"/"Game Boy Advance" or "PlayStation"/PlayStation Portable") showing up in arbitrary order, and that order changing after reboots (as `qsort` likely isn't a stable sort, and it's not clear what order we get the names from the filesystem API anyway).
I don't have a muOS dev environment set up at the moment, but I verified the bug and fix in …
=> Fix str_compare when one string is a prefix of the other

common/device.c, common/device.h, lvgl/drivers/display/fbdev.c, lvgl/drivers/display/fbdev.h, lvgl/src/core/lv_disp.c, lvgl/src/core/lv_disp.h, lvgl/src/hal/lv_hal_disp.c
HDMI was not working quite well in rotated screens (RG28XX). this was thought to be configurable with a simple fbset but unfortunatly was impossible as the result was a screen with edges being turnicated. 
There are few possible fixes for this:
- Upgrade lvgl to v9 which handles rotation better . This is quite a pain as lvgl has changed a lot of their display initialization process which in turn force us to change the logic for every single mux app. 
- compile the whole mux apps with sdl driver as rotations will be handeled by the patched SDL lib . This was my last resort if nothing worked. 
- Modify the buffer writing algorithm and include an hdmi check. which what have been done here. 
The main culprit for the restricted hdmi output (screen being cut from edges) was that lvgl pulls the …
=> Adding hdmi support for rotated devices (RG28XX for now).

muxplore/main.c
Updated context explorer to display long item names with an ellipse but then auto switch to a circular scroll when the item has focus
=> muOS Frontend - Add scrolling text to context explorer

muxplore/theme.c, muxplore/ui/ui_scrExplore.c
* Fixed issue with image preview using wrong setting for radius.
* Fixed issue with Image_list_radius only applying the radius to the background and not the image itself
=> muOS Frontend - Theme Image List Settings

common/common.c
* The strings being sorted no longer have extensions, but we try to strip them out anyway. This messes up the sort order when ROM names have `.` chars in them since we truncate file names incorrectly and fail to look up the mtime.
* With this change, sort order in the UI matches mtime of the files (e.g., `ls -lt /mnt/sdcard/MUOS/info/history`). Note that if mtime is wrong due to incorrect system clock, this of course won't help. :)
* Also frees the dup'd strings, which fixes a small memory leak (probably not super consequential, but while I'm in here).
=> Fix sorting of history list entries with dots in the name

muxlaunch/main.c
New NAVIGATION_TYPE == 3 which, once again, is primarily horizontal scrolling, but this one is designed around a two row layout with 3 items in the first row, and 5 items in the second row. Useful for these themes:
Also, upgraded the two rows of 4 mode to only jump down if on the first row and only jump up if on the second row.
=> Horizontal Navigation with 3 item first row, 5 item second row

muxlaunch/main.c
* NAVIGATION_TYPE 4 = same as type 2 but wrapping is locked to the row so if I'm on Apps and hit next it wraps around Explore instead of going to info
* NAVIGATION_TYPE 5 = same as type 3 but wrapping is locked to the row so if I'm on History and hit next it wraps around Explore instead of going to apps
=> muOS Frontend - New Navigation Types

common/theme.c, common/ui_common.c, muxplore/main.c
* when refactoring themes picked the wrong screen width and height setting
* fixed issue with game names being blank if general.json does not exist
=> RG28XX Crop Fix / Blank names Fav History

common/common.c
If Interface Font Type is set to 'Noto Sans' system will check to see if a bin file exists in the language folder matching the selected language name and use that for the font
=> added support for auto loading custom font

common/common.c
The idea behind this is that a theme creator that designs the theme to use images for the main menu can choose to support multiple language in one theme.  Example main images stored in:
/mnt/sdcard/MUOS/theme/active/image
images used when German language is selected would be stored in:
/mnt/sdcard/MUOS/theme/active/image/German
if any language images do not exist it will fall back to main images
=> Update theme engine to support wallpapers for each language

common/common.c
This changes the voltage string formatting from `x.xxv` to `x.xx V`.
~~I realize this is nitpicky but it's been bugging me~~
=> Changed the charge screen voltage string formatting

muxtheme/main.c
Fixed issue with preview images for themes not displaying due to LVGL image cache
=> fix theme preview images

common/common.c, muxassign/main.c, muxgov/main.c, muxplore/main.c
Updated to look for skip.ini in the /info/config/ folder so that it can be loaded from bind mounts
=> move skip.ini to config

common/device.h, muxapp/main.c, muxarchive/main.c, muxassign/main.c, muxconfig/main.c, muxgov/main.c, muxinfo/main.c, muxlanguage/main.c, muxlaunch/main.c, muxnetprofile/main.c, muxnetscan/main.c, muxnetwork/main.c, muxoption/main.c, muxpass/main.c, muxplore/main.c, muxrtc/main.c, muxstorage/main.c, muxsysinfo/main.c, muxtask/main.c, muxtester/main.c, muxtheme/main.c, muxtimezone/main.c, muxtweakadv/main.c, muxtweakgen/main.c, muxvisual/main.c, muxwebserv/main.c
Turns out that when comparing signed and unsigned ints of the same size, [C converts the signed value to unsigned and does an unsigned comparison](https://stackoverflow.com/a/70642482/152208). Of course, this doesn't work well when the signed value can be negative (like `ev.value` we get for joystick inputs, which is negative over half the axis). This leads to comparisons giving absurd and very confusing results.
The easiest fix that doesn't involve adding casts all over the place is just changing the `AXIS` config value to a signed `int32_t`. (It looks like all the other config values are already signed anyway.) Then the comparisons behave as expected and we don't seem to need so many sanity checks (which it turns out were behaving differently than expected).
Also a quick code …
=> Fix signed/unsigned comparison bug with device.INPUT.AXIS

muxapp/main.c, muxarchive/main.c, muxassign/main.c, muxconfig/main.c, muxgov/main.c, muxinfo/main.c, muxlanguage/main.c, muxnetprofile/main.c, muxnetscan/main.c, muxnetwork/main.c, muxoption/main.c, muxplore/main.c, muxrtc/main.c, muxstorage/main.c, muxsysinfo/main.c, muxtask/main.c, muxtheme/main.c, muxtimezone/main.c, muxtweakadv/main.c, muxtweakgen/main.c, muxvisual/main.c, muxwebserv/main.c
This change makes scrolling and acceleration behave the same on my device with Hall-effect sticks (cheap AliExpress K-Silvers) as it does on my device with stock sticks. Additionally, with this change, failure of the stick to fully center (due to lack of deadzone) no longer interrupts acceleration when scrolling with the D-pad.
Note that this still assumes the stick can reach the max axis value (4096 by default). For sticks that can't physically reach the full range, changing the `AXIS` config value might help... but they'll likely cause issues in emulators too, so this may not be worth worrying about.
Incidentally, this change also reenables scrolling left and right in the settings menus with the stick, which there was already code for, but seems to have broken at some point. :)
---
The …
=> Overhaul menu acceleration to improve Hall-effect stick compatibility

muxtester/main.c
Currently, the input tester behaves strangely for sticks that have jitter around the center point, like the Hall-effect sticks too. This change fixes that so that folks can use it to see if their Hall stacks can hit the full axis range or not.
(Fun fact, in all this testing I found out one of my cheap AliExpress sticks can't hit the whole range either! Swapped it for an extra and it seems fine. Clearly some hardware variation out there...)
=> Make muxtester compatible with Hall sticks

common/input.c, common/input.h, muxlaunch/Makefile, muxlaunch/main.c, muxplore/Makefile, muxplore/main.c, muxtester/Makefile, muxtester/main.c
I was trying to tweak the stick direction detection and menu acceleration a bit more, and I kept getting frustrated by the duplication of input handling code across the various apps, plus the entanglement of the app logic directly in the evdev loop (which makes it hard to add deadzones and things without making the app-specific logic really complex).
I started prototyping an abstraction layer between evdev and the apps themselves, and... I got a little carried away. 😄 I wound up factoring the core event loop, evdev decoding logic, press/hold detection, etc. into a reusable library (`input.c`/`input.h`). It provides an "input task" that a muX app can configure, registering handlers for press, release, and hold actions on specific buttons and inputs.
The idea is that if we want to change …
=> Reusable input handling library

common/theme.c, common/theme.h, muxplore/main.c
The built in LVGL logic for auto ellipsing would leave a lot of unused space at the end.  Updated to use our own method to calculate and set ellipse.
=> add method for manually doing ellipse

common/input.c, muxapp/Makefile, muxapp/main.c, muxarchive/Makefile, muxarchive/main.c, muxinfo/Makefile, muxinfo/main.c, muxlaunch/main.c, muxplore/main.c, muxsysinfo/Makefile, muxsysinfo/main.c
1. Sets analog stick detection threshold to 80% of the nominal max axis value. This should help with sticks (like the inconsistent Hall-effect ones) that can't quite reach the full axis value. Doesn't seem to introduce any sensitive issues on stock sticks.
2. Decouples gamepad event loop delay from menu acceleration delay. We can do this since we now track pending input hold times separately from the `epoll_wait` that controls the input loop. This fixes an interesting bug where the screen update rate is tied to acceleration rate. (The bug is easy to see in muxsysinfo. If you disable menu acceleration in settings, then the sysinfo stats don't update until you press a button.)
3. Ports a few more apps to the new input library so they can benefit from the above. :)
=> Tweak new input library and port a couple more apps over to it

common/theme.c
added themeoverrides.txt to allow the user to override FONT_LIST_PAD_RIGHT and CONTENT_WIDTH of a theme.  This will be useful for users that are displaying boxart and do not want the list item text to get covered by the box art.  More settings can be added later if a need arises.
=> add option to override specific theme options

Makefile
Otherwise, make errors out and doesn't finish cleaning up the tmp files.
=> Don't error out if notify-send is missing (or fails)

common/ui_common.c
when swap A+B is enabled the wrong glyph is displayed on the help screen for toggling between preview and text
=> fix preview toggle

Makefile, common/common.h, common/input.c, common/input.h, common/ui_common.c, common/ui_common.h, muhotkey/Makefile, muhotkey/main.c, muxapp/main.c, muxarchive/main.c, muxconfig/main.c, muxinfo/main.c, muxlaunch/main.c, muxplore/main.c, muxrtc/main.c, muxsysinfo/main.c, muxtester/main.c, muxtimezone/main.c
I wanted combo support when porting apps over to the new input library. It gives a more general way to handle things like the brightness keys, and is one of the last big things I wanted to call the library "complete".
I made some simplifying assumptions to help keep things sane. For example, only one combo can be active at a time, because combo press/hold/release behavior gets really confusing with multiple overlapping combos triggered at once.
To test this, I migrated the volume and brightness handlers of the muX apps using the new input library. But that's mostly just a precursor for the next thing....
---
I've written a `muhotkey` C program to listen for hotkeys from `input.sh` in the shell scripts. I have a soft spot for the `evtest` loop, but it has some disadvantages:
* It burns a …
=> Implement input combos and a muhotkey program for scripts

common/common.c, common/common.h, muxplore/main.c
if new config file exists it will allow the user to configure up to 5 images to use as box art. If config file does not exist it will fallback to default boxart loading.
=> Advance box art config

muhotkey/main.c
One-word fix for a _weird_ bug. Did you know `CLOCK_REALTIME` jumps around when the RTC changes? This meant that with the new idle implementation, we accidentally dimmed the display whenever the RTC/timezone apps were opened....
It looks like `CLOCK_MONOTONIC` stays, well, monotonic even when the system time changes. (I think we want this for all the muX apps, since presumably `mux_tick()` going back in time will mess with the LVGL timers, but I wanted to fix the one bug I found for the idle stuff first.)
=> Use CLOCK_MONOTONIC in muhotkey to avoid idle bug

common/input/list_nav.c, common/input/list_nav.h, muxapp/Makefile, muxapp/main.c, muxarchive/Makefile, muxarchive/main.c, muxconfig/Makefile, muxconfig/main.c, muxinfo/Makefile, muxinfo/main.c, muxplore/Makefile, muxplore/main.c, muxrtc/Makefile, muxrtc/main.c, muxsysinfo/Makefile, muxsysinfo/main.c, muxtimezone/Makefile, muxtimezone/main.c, muxtweakgen/Makefile, muxtweakgen/main.c
This is a second attempt at #88, without the cleanups bogging it down, as well as an implementation requiring less changes to the existing apps (and less code overall!). This PR is the last step to make it easy to port all the remaining apps over (with minimal risk of introducing new scrolling bugs in the process).
The `list_nav.h` input handlers standardize on the following behavior:
* Up/Down (press): Scroll one item at a time, wrapping around at the start/end.
* Up/Down (hold): Scroll one item at a time, but stop scrolling at the start/end.
* L1/R1 (press/hold): Scroll one page of items at a time, stopping at the start/end.
@GrumpyGopher The only significant app change required to use these handlers is making `list_nav_prev`/`list_nav_next` wrap around at the end like the underlying …
=> Factor out list nav handlers & port muxtweakgen to new input lib

muxapp/main.c, muxcharge/Makefile, muxcharge/main.c, muxcredits/Makefile, muxcredits/main.c, muxnetwork/Makefile, muxnetwork/main.c, muxpass/Makefile, muxpass/main.c
Ports over a few apps some unusual input setups, mostly for completeness. Together with the @GrumpyGopher's #93, this is all of them. :D
`muxpass`: I also changed some error exit statuses from 1 (password check succeeded) to 2 (password check failed) so an error doesn't let someone through without a password. (Maybe it should just be 0 -> success and 1 -> failure to be more standard, but I didn't want to change the companion scripts right now.)
`muxnetwork`: Came out messier than I'd like due to the on-screen keyboard, but this seems to work for now, and the structure can always be improved later.
In particular, it should be possible to create APIs for swapping out the input handler configs when a modal dialog is shown (like the help message box or the on-screen keyboard). Just needs a …
=> Port apps with edge cases to new input library

common/common.c
Fixes the recent `muxcredits` timeout issue. (More generally, likely fixes some odd wraparound issues with long timers.)
=> Fix mux_tick start point to avoid wraparound issue

common/input.c, common/input.h
I think @antiKk is using this setting to swap ABXY in the SDL configs, so it seemed to make sense to swap the X&Y buttons for the muX apps too. WDYT?
I also added `void` to a couple of function prototypes because I keep forgetting this is C, not C++, and `()` is different from `(void)`....
=> Swap X&Y when pref is set, not just A&B

common/common.c, common/common.h, common/input.h, common/ui_common.c, muhotkey/main.c, muxapp/main.c, muxarchive/main.c, muxcharge/main.c, muxnetscan/main.c, muxtask/main.c, muxtheme/main.c
Requires companion PR to be merged at the same time: https://github.com/MustardOS/internal/pull/300
* Changes `/run/muos/system/idle_inhibit` to a normal "variable file" with values 0/1 instead of just checking file presence. Same effect, but is more consistent with other muOS flags in the filesystem.
* Updates `muhotkey` to only read the `idle_inhibit` file if it _didn't_ just process an input event. Otherwise, we end up reading the file uselessly in a tight loop and wasting CPU when receiving continuous inputs like stick movement.
* Adds a new `read_int_from_file(name)` function for the common pattern of `atoi(read_line_from_file(name, 1))`. It's a microscopic bit faster since it saves an allocation, but more importantly, it fixes a memory leak (since the apps currently use …
=> Improve input/idle handling & fix a memory leak

muxnetwork/main.c
[Bug report on Discord](https://discord.com/channels/1152022492001603615/1292582523376894072)
It's not broken for the password field since we don't try to initialize from existing text for that case. I guess that's the only one I tested.
=> Fix segfault in muxnetwork when opening keyboard

common/common.c, common/common.h, muxapp/main.c, muxarchive/main.c, muxassign/main.c, muxconfig/main.c, muxgov/main.c, muxinfo/main.c, muxlanguage/main.c, muxlaunch/main.c, muxnetprofile/main.c, muxnetscan/main.c, muxnetwork/main.c, muxoption/main.c, muxpass/main.c, muxplore/main.c, muxpower/main.c, muxrtc/main.c, muxstorage/main.c, muxsysinfo/main.c, muxtask/main.c, muxtester/main.c, muxtheme/main.c, muxtimezone/main.c, muxtweakadv/main.c, muxtweakgen/main.c, muxvisual/main.c, muxwebserv/main.c
On some screens init elements gets called more than once causing the overlay to be applied multiple times making the screen darker than expected
=> fix issue with overlay being applied twice

Makefile
Alternatively, should I rename `muhotkey` to `muxhotkey`? I initially thought the `mux` binaries were the GUI apps, whereas the `mu` binaries (like `mushutdown` we used to have) where CLI utilities, but now I'm not so sure. :)
=> Remove muhotkey on `make clean`

muxnetscan/main.c
Missed this one in #113. Need to set _GNU_SOURCE for pthread_tryjoin_np to get defined in pthread.h.
=> Fix implicit-function-declaration in muxnetscan

common/common.c, common/common.h, common/ui_common.c, muxapp/main.c, muxarchive/main.c, muxassign/main.c, muxconfig/main.c, muxgov/main.c, muxinfo/main.c, muxlanguage/main.c, muxlaunch/main.c, muxnetprofile/main.c, muxnetscan/main.c, muxnetwork/main.c, muxoption/main.c, muxplore/main.c, muxpower/main.c, muxrtc/main.c, muxstorage/main.c, muxsysinfo/main.c, muxtask/main.c, muxtheme/main.c, muxtimezone/main.c, muxtweakadv/main.c, muxtweakgen/main.c, muxvisual/main.c, muxwebserv/main.c
As [reported on Discord](https://discord.com/channels/1152022492001603615/1297926619838550048), the icon in the volume popup gets one step out of sync with the progress bar. (It's most noticeable with the "mute" icon when the volume gets turned out to zero.)
Happens because we update the volume _level_ on every file, but we only update the _icon_ in the input handler. We're already reading the volume file in `update_bars`, so moving the icon update there resolves that issue. Now the "mute" icon shows up only when the volume bar is showing zero.
Additionally, we may as well skip reading `brightness.txt` and `volume.txt` when the relevant bar isn't onscreen. (It's not super expensive, but saving two file reads each frame can't hurt.)
=> Fix volume icon getting out of sync with progress bar

common/common.c, common/common.h, common/input.h, muhotkey/Makefile, muhotkey/main.c
Now that system hotkeys are configured via a JSON file, it makes sense for `muhotkey` to parse them directly rather than `hotkey.sh` having to convert the JSON file to the existing command-line format.
Additionally, it's inconvenient to need to order the hotkeys correctly by hand. (And in case we ever do want to have a GUI app to configure hotkeys, we won't be able to rely on a specific ordering.)
Instead, this change makes `muhotkey` sort combos from longest (most keys) to shortest (least keys), so that e.g. VOL_UP+MENU_LONG is always checked before VOL_UP (regardless of their order in the JSON file).
I also made a few other minor code cleanups while I'm in here.
=> Parse from JSON and auto-sort combos in muhotkey

common/options.h
`/opt/muos/default/MUOS/theme` is a full copy of the default themes (plural) for the [restore script](https://github.com/MustardOS/internal/blob/3f4f5e726e9ab6fe2dddca757417b86fd7cbad28/init/MUOS/task/Restore%20Themes.sh).
So the unzipped copy of the initially active theme for fallback purposes lives in the subdirectory at `/opt/muos/default/MUOS/theme/active`.
---
For reference, here is where `default/MUOS/theme` is populated for the [rootfs](https://github.com/MustardOS/tool/blob/3d26eb2980cc312aea4eb9fb7f2d1cbef7ea1465/update_rootfs.sh#L62) and [updates](https://github.com/MustardOS/tool/blob/3d26eb2980cc312aea4eb9fb7f2d1cbef7ea1465/gen_update.sh#L140).
=> Add /active suffix to fallback theme path

common/font/notosans.c
Some of the preprocessor directives got split across two lines somehow.
=> Fix notosans.c build

common/common.c
For the display of random backgrounds based on PNG sequences, this change puts the last image in the sequence within range for random selection
=> Increase upper bound on random image range

muxnetprofile/main.c, muxnetwork/main.c
I've tested this with a blank password profile and a regular password profile, in addition to connecting to a passwordless DHCP network after scanning.
=> add support for empty wifi passwords

common/theme.c, common/theme.h
This unfortunately named branch adds support for vertical gradients.
I also took the liberty of moving the `LIST_FOCUS` struct to an earlier place in the `theme.h` file to be next to the `LIST_DEFAULT` struct.
The new settings expect an int set to either 0 or 1, standing for horizontal and vertical gradients respectively. They default to 0 to not break existing themes.
This functionality is currently untested because I lack the ability to create my own builds.
=> Added LIST_*_GRADIENT_DIRECTION settings to the theme schema [list] section

common/theme.c, common/theme.h
LIST_DEFAULT_BORDER_WIDTH = width of border
LIST_FOCUS_BORDER_WIDTH = width of border for selected item 
LIST_DEFAULT_BORDER_SIDE and LIST_FOCUS_BORDER_SIDE set where the border is displayed 
0=None
1=Bottom
2=Top
4=Left
8=Right
15=All
add values up to do more than one side for example a value of 3 would do top and bottom
=> add theme settings for list item border

common/common.c, common/common.h, common/theme.c, common/theme.h
- Added a way to control the repetition count for background animations via ANIMATION_REPEAT property in [animation] section
- It defaults to 0 which is the previous default behavior (infinite loop)
- If set to anything bigger than that, the background will loop only that amount of times
- This setting will do nothing for GIF backgrounds, as LVGL doesn't have a way to control the repeat count in GIFs
This opens up a way to create enter animations in themes.
=> Add animation repeat count setting for themes

module/muxnetprofile.c
My home network has WiFI SSIDs along the lines of `network/fast` and `network/iot` that would silently fail to save as a network profile because the slash would be included in the profiles file name.
This PR fixes this by replacing `/` and `\` characters with underscores when saving a network profile based on an SSID that includes them.
=> Sanitize slash characters in new network profile names

module/muxhistory.c
This was already removed from content explorer and collections when loading a game removing from history for consistency
=> remove loading message from history

common/theme.c, module/muxtester.c
set content width to screen width when set to 0
=> fix input tester detecting left stick as dpad

module/muxapp.c, module/muxarchive.c, module/muxconnect.c, module/muxcustom.c, module/muxtask.c
* fixed issue with size to content setting wrong width on Applications and Task Toolkit screens when using language other than English
* fixed issue with size to content not being disabled on Connectivity and Customization screens
* fixed issue with size to content setting incorrect width on Archive Manager due to not excluding file extension
=> fix size to content issues

common/language.c
Updated MUXPOWER.HELP.SLEEP_FUNCTION description to say "short press" instead of "long press (2 seconds)" as per altered behaviour in 2508.0 Goose.
=> Updated Sleep Function description
