MustardOS/frontend

common/theme.c
common/theme.h
muxplore/main.c
muxplore/theme.c
muxplore/ui/ui.c
muxplore/ui/ui.h
muxplore/ui/ui_scrExplore.c

Added file counter to context explorer

muOS Frontend - File Counter

---

muxcharge/main.c

Allows clean shutdown from the charger scripts. This appears to be the last hardcoded `reboot` in the frontend except the one in `muxdevice` (but I think that might be dead code now that the images are device specific?).
Requires companion PR https://github.com/MustardOS/internal/pull/147 as currently `charge.sh` always does full boot regardless of `muxcharge` success/failure.

Rather than reboot in muxcharge directly, exit with status 1 on cable removal

---

common/theme.c
common/theme.h
muxapp/main.c
muxapp/theme.c
muxassign/main.c
muxassign/theme.c
muxconfig/main.c
muxconfig/theme.c
muxconfig/ui/ui_scrConfig.c
muxinfo/main.c
muxinfo/theme.c
muxinfo/ui/ui_scrInfo.c
muxlaunch/main.c
muxlaunch/theme.c
muxlaunch/ui/ui_scrLaunch.c
muxnetprofile/main.c
muxnetprofile/theme.c
muxnetscan/main.c
muxnetscan/theme.c
muxplore/main.c
muxplore/theme.c
muxtask/main.c
muxtask/theme.c
muxtheme/main.c
muxtheme/theme.c
muxtimezone/main.c
muxtimezone/theme.c

* theme->MISC.CONTENT.SIZE_TO_CONTENT = Resizes items in content panel to fit contents.  Respects theme->MISC.CONTENT.WIDTH as a max width theme->MISC.CONTENT.ALIGNMENT = Align items 0 left 1 center 2 right

muOS Frontend - New Theme engine settings

---

common/theme.c
common/theme.h
muxapp/main.c
muxarchive/main.c
muxassign/main.c
muxconfig/theme.c
muxinfo/theme.c
muxlaunch/theme.c
muxnetprofile/main.c
muxnetscan/main.c
muxnetwork/theme.c
muxplore/main.c
muxrtc/theme.c
muxstorage/theme.c
muxsysinfo/theme.c
muxtask/main.c
muxtheme/main.c
muxtimezone/main.c
muxtweakadv/theme.c
muxtweakgen/theme.c
muxvisual/theme.c
muxwebserv/theme.c

added new theme settings to [font] section for
* FONT_LIST_PAD_LEFT
* FONT_LIST_PAD_RIGHT

muOS Frontend - List Text Padding

---

muxlanguage/main.c
muxnetprofile/main.c
muxnetscan/main.c

* removed gen_item_thread from muxlanguage and muxnetprofile
* updated muxnetscan to avoid segmentation faults

fix threading issues

---

muxplore/main.c

Fixed issue with info text not being displayed in Content Explorer

muOS Frontend

---

lvgl/src/extra/libs/gif/lv_gif.c
muxvisual/main.c

Fixed issue with ui_count being incorrect causing navigation wrap around to skip entries

muxvisual navigation fix

---

muxapp/main.c
muxarchive/main.c
muxassign/main.c
muxconfig/main.c
muxgov/main.c
muxinfo/main.c
muxlanguage/main.c
muxlaunch/main.c
muxnetprofile/main.c
muxnetscan/main.c
muxnetwork/main.c
muxoption/main.c
muxplore/main.c
muxrtc/main.c
muxstorage/main.c
muxsysinfo/main.c
muxtask/main.c
muxtheme/main.c
muxtimezone/main.c
muxtweakadv/main.c
muxtweakgen/main.c
muxvisual/main.c
muxwebserv/main.c

disable displaying help menu when screenshot is taken

Screenshot suppress help

---

common/theme.c
common/theme.h
common/ui_common.c

auto center items in header vertically

auto center items in header vertically

---

common/common.c

updated font loading to fallback to language font

add fallback font support

---

muxplore/main.c

Title will now see if there is a friendly name defined for the volume label and use that.  Also added checks for if Volume Label is blank.

added friendly name look up to volume label

---

muxplore/main.c

* fix Segmentation fault happening when opening content explorer on dual SD card setup.
* fix issue with preview text for folders looking in catalogue/root instead of catalogue/folder

fix Segmentation fault

---

muxplore/main.c

These were not needed with how it loads the images and was causing some weird glitch were regular box art was not displaying

remove unnecessary add and clear flags

---

muxassign/Makefile
muxassign/main.c
muxgov/Makefile
muxgov/main.c
muxlanguage/Makefile
muxlanguage/main.c
muxoption/Makefile
muxoption/main.c
muxtask/Makefile
muxtask/main.c
muxtheme/Makefile
muxtheme/main.c
muxtweakadv/Makefile
muxtweakadv/main.c
muxtweakgen/main.c
muxvisual/Makefile
muxvisual/main.c
muxwebserv/Makefile
muxwebserv/main.c

refactor muxlanguage, muxoption, muxtask, muxtheme, muxassign, muxgov, muxvisual, muxtweakadv, muxwebserv to use new input methods

input refactor

---

muxplore/main.c

* updated favourites button to toggle between adding and removing favourite
* updated to refresh glyph icon on change
* added fade to screen message when adding or removing favourite

add toggle favourite

---

muxpower/main.c

[Bug report on Discord](https://discord.com/channels/1152022492001603615/1292500741705170996)

Fix off-by-one in muxpower settings load

---

muxconfig/main.c
muxinfo/main.c
muxlaunch/main.c
muxnetwork/main.c
muxoption/main.c
muxplore/main.c
muxpower/main.c
muxstorage/main.c
muxsysinfo/main.c
muxtweakadv/main.c
muxtweakgen/main.c
muxvisual/main.c
muxwebserv/main.c

* fix typo in muxplore
* update help screens so translations can be scraped properly

translation fixes

---

common/common.c
muxplore/main.c

fixed issue where favourite and history box art would not display when using advanced boxart config

fix advance artwork config issue

---

common/ui_common.c
muxtheme/main.c

fixed issue with wall paper being shifted down.
fixed issue with theme picker preview displaying then hiding

fix wallpaper and muxtheme preview

---

common/controller_profile.c
common/controller_profile.h
common/input.c

* update controller profile name to include vendor and product id 
* add controller support for DPADs that register as buttons

controller support updates

---

common/common.c
common/theme.c
common/theme.h
common/ui_common.c
common/ui_common.h
module/muxapp.c
module/muxlaunch.c
module/muxplore.c

Added options for setting up a floating label that will display the text of the currently selected item when using Grid Mode in a theme

Add Grid Mode current item label

---

common/mini/mini.c

Updated load method to properly handle files with carriage returns

add CRLF support for Ini files

---

common/common.c
common/common.h
common/input.c
common/input.h
module/muxcollect.c
module/muxhistory.c
module/muxplore.c

- fixed issue with box art displaying for collection folder 
- fixed issue with description displaying for collection folder 
- fixed keyboard navigation when using grid mode

Collection Fixes

---

common/common.c
module/muxapp.c
module/muxcollect.c
module/muxhistory.c
module/muxplore.c
module/muxsearch.c

refactored all box art methods to use load_image_catalogue method

add resolution support for box art images

---

common/theme.c

fix issue with using HDMi theme resolution if current theme does not support the current HDMI resolution

fix HDMI theme resolution

---

lookup/lookup_d.c
lookup/lookup_k.c
lookup/lookup_m.c
lookup/lookup_n.c
lookup/lookup_p.c
lookup/lookup_s.c

adds a few full names into the lookup files for some arcade games I noticed were missing

add full names for some arcade games

---

common/common.c

updated the path to sdcard location of skip.ini to match search feature

add sdcard skip.ini check

---

common/common.c
common/language.c
common/language.h
common/options.h
common/theme.c
common/theme.h
common/ui_common.c
module/muxcollect.c
module/muxcustom.c
module/muxhistory.c
module/muxlaunch.c
module/muxpicker.c
module/muxplore.c
module/muxsearch.c
module/ui/ui_muxcustom.c
module/ui/ui_muxcustom.h

This reverts commit 08a368a1e5948f87469190bb86e91e29f457ff65.

Revert "update theme loading to use new Pixie theme structure (#190)"

---

common/theme.c
module/muxcustom.c
module/muxlaunch.c

* sorted options for alternate themes
* fixed navigation bugs in grid mode

sort alternate theme drop down

---

module/muxconnect.c
module/muxcustom.c

fixed issue where pressing A to update a setting in Customisation would exit the menu instead of updating the value

fix issue exiting customisation menu

---

common/init.c
common/theme.c
lvgl/src/drivers/display/sdl.c
module/muxhdmi.c

fix hdmi scaling at all hdmi resolutions

---

module/muxoption.c

only applies to themes that have a low item count set for the content options screen

fix issue with scrolling to all content options

---

module/muxrtc.c

- Added additional safety checks
- Fixed minor bug with changing month but day not changing to a valid day

muxrtc Refactor

---

common/common_core.c
module/muxplore.c

add fallback to catalogue for content description text

fix issue with fallback to catalogue name for Folder box art
